os: linux
language: ruby
cache:
  directories:
    - /home/travis/.rvm/
rvm:
  - 2.4.9
  - 2.5.1
  - 2.6.2
script:
  - gem install bundler
  - bundle install
  - bundle exec rspec
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile