os: linux
language: ruby
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2' || true
rvm:
  - 2.5.3
script:
  - gem install bundler -v '1.17.3'
  - bundle _1.17.3_ install --gemfile=gemfiles/rails_4.gemfile
gemfile:
  - gemfiles/rails_4.gemfile